name: Build and Scan Docker Image

on: [push]

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: frontend
  IMAGE_TAG: latest

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG . 
        
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 1
          ignore-unfixed: true
      
      - name: Log into ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push Docker image
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG 940622738555.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          docker push 940622738555.dkr.ecr.eu-west-2.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG


          