name: Deploy to ECS 

on:
  workflow_run:
    workflows: ["Build and Scan Docker Image"]
    types:
      - completed
    
env:
  AWS_REGION: eu-west-2
  ECS_CLUSTER: ecs_cluster
  ECS_SERVICE: frontend-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
        
      - name: New ECS deployment (by force)
        run: |
          aws ecss update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE \
          --force-new-deployment --region $AWS_REGION 