name: Terraform Plan

on:
  push:
  workflow_dispatch:

env:
    AWS_REGION: eu-west-2
    TF_VERSION: 1.7.0

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v3
        
        - name: Set up terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: ${{ env.TF_VERSION }}
        
        - name: Config AWS credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}
        
        - name: Terraform Init
          run: terraform init

        - name: Terraform Format Check
          run: terraform fmt -check
        
        - name: TFLint
          uses: terraform-linters/setup-tflint@v4
        - run: tflint

        - name: Run Checkov Security scan
          uses: bridgecrewio/checkov-action@master
          with:
            directory: ./terraform
            quiet: true

        - name: Terraform plan
          run: terraform plan
